import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Work_Sans } from "next/font/google";

const work_header = Work_Sans({
  weight: ["900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const work_bread = Work_Sans({
  weight: ["900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${work_header.className} bg-blue  w-full max-w-none`}>
        <header>
          <Navbar />
        </header>
        <main className="justify-center flex px-2 py-10 md:px-7">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
